from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np


@dataclass(frozen=True)
class ArrayPoint:
    """Physical antenna element coordinate."""

    name: str
    x: float
    y: float


@dataclass(frozen=True)
class VirtualPoint:
    """Virtual antenna element coordinate generated by one Tx/Rx pair."""

    tx_name: str
    rx_name: str
    x: float
    y: float


class AntennaArray:
    def __init__(self, tx: Iterable[ArrayPoint], rx: Iterable[ArrayPoint]) -> None:
        self.tx = tuple(tx)
        self.rx = tuple(rx)
        if not self.tx:
            raise ValueError("tx must contain at least one element")
        if not self.rx:
            raise ValueError("rx must contain at least one element")

    @classmethod
    def from_xy(
        cls,
        tx_x: Iterable[float],
        tx_y: Iterable[float],
        rx_x: Iterable[float],
        rx_y: Iterable[float],
    ) -> "AntennaArray":
        tx_x_values = tuple(tx_x)
        tx_y_values = tuple(tx_y)
        rx_x_values = tuple(rx_x)
        rx_y_values = tuple(rx_y)

        if len(tx_x_values) != len(tx_y_values):
            raise ValueError("tx_x and tx_y must have the same length")
        if len(rx_x_values) != len(rx_y_values):
            raise ValueError("rx_x and rx_y must have the same length")

        tx = [
            ArrayPoint(name=f"Tx{i}", x=float(x), y=float(y))
            for i, (x, y) in enumerate(zip(tx_x_values, tx_y_values), start=1)
        ]
        rx = [
            ArrayPoint(name=f"Rx{i}", x=float(x), y=float(y))
            for i, (x, y) in enumerate(zip(rx_x_values, rx_y_values), start=1)
        ]
        return cls(tx=tx, rx=rx)

    def subset(
        self,
        tx_indices: Iterable[int] | None = None,
        rx_indices: Iterable[int] | None = None,
    ) -> "AntennaArray":
        tx = self.tx if tx_indices is None else tuple(self.tx[i] for i in tx_indices)
        rx = self.rx if rx_indices is None else tuple(self.rx[i] for i in rx_indices)
        return AntennaArray(tx=tx, rx=rx)

    def horizontal_subset(self, tx_y: float = 0.0, rx_y: float = -10.0) -> "AntennaArray":
        tx = tuple(point for point in self.tx if point.y == tx_y)
        rx = tuple(point for point in self.rx if point.y == rx_y)
        return AntennaArray(tx=tx, rx=rx)

    def tx_xy(self) -> np.ndarray:
        return _points_to_xy(self.tx)

    def rx_xy(self) -> np.ndarray:
        return _points_to_xy(self.rx)

    def virtual_points(self, scale: float = 1.0) -> tuple[VirtualPoint, ...]:
        return tuple(
            VirtualPoint(
                tx_name=tx.name,
                rx_name=rx.name,
                x=(tx.x + rx.x) * scale,
                y=(tx.y + rx.y) * scale,
            )
            for tx in self.tx
            for rx in self.rx
        )

    def virtual_xy(self, scale: float = 1.0) -> np.ndarray:
        return _virtual_points_to_xy(self.virtual_points(scale=scale))

    def unique_virtual_xy(
        self,
        scale: float = 1.0,
        decimals: int = 9,
    ) -> tuple[np.ndarray, np.ndarray]:
        xy = self.virtual_xy(scale=scale)
        rounded = np.round(xy, decimals=decimals)
        unique, counts = np.unique(rounded, axis=0, return_counts=True)
        return unique, counts

    def summary(self, scale: float = 1.0) -> dict[str, object]:
        unique, counts = self.unique_virtual_xy(scale=scale)
        duplicate_counts = counts[counts > 1]
        return {
            "tx_count": len(self.tx),
            "rx_count": len(self.rx),
            "virtual_count": len(self.tx) * len(self.rx),
            "unique_virtual_count": int(len(unique)),
            "duplicate_location_count": int(len(duplicate_counts)),
            "max_multiplicity": int(counts.max()) if len(counts) else 0,
        }


def _points_to_xy(points: Iterable[ArrayPoint]) -> np.ndarray:
    return np.array([(point.x, point.y) for point in points], dtype=float)


def _virtual_points_to_xy(points: Iterable[VirtualPoint]) -> np.ndarray:
    return np.array([(point.x, point.y) for point in points], dtype=float)
